### ISSUE TITLE
Show active timers - even if they were started yesterday

### ISSUE THREAD

**Issue by CaCtus491** [jkraemer/stopwatch#5]
Just installed this plugin yesterday and love the functionality.

I've run into an issue just now where I started a timer against an issue prior to midnight, then went to stop it shortly after midnight. The active timer was no where to be seen. I was able to stop the timer by going to the time tracking for the issue and stopping it there, however it'd be great if the popup window showed the active timer, even if it has been active since the previous day :)

**Comment by jkraemer** [comment]
Good point, fixed!
